"use client";
import { FormEvent, useEffect, useState } from "react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { supabase } from "@/lib/supabase";

type Profile = { id: string; email: string; role: string; magasin_id: string | null; admin_scope: string | null; actif: boolean; created_at: string | null };
export default function Page() { const [profiles,setProfiles]=useState<Profile[]>([]); const [open,setOpen]=useState(false); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState("RR"); const [magasinId,setMagasinId]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const charger=async()=>{const {data}=await supabase.from("profiles").select("id,email,role,magasin_id,admin_scope,actif,created_at").order("created_at",{ascending:false});setProfiles((data??[]) as Profile[])};useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
 void charger()},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");const {data:{session}}=await supabase.auth.getSession();const res=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify({action:"create",email,password,role,magasinId:magasinId||null,adminScope:role==="ADMIN"?"MAGASIN":null})});const data=await res.json();setLoading(false);if(!res.ok){setMessage(data.error??"Erreur");return}setOpen(false);setEmail("");setPassword("");void charger()}
 async function toggle(profile:Profile){const {data:{session}}=await supabase.auth.getSession();const res=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify({action:"toggle",userId:profile.id,actif:!profile.actif})});const data=await res.json();if(!res.ok)setMessage(data.error??"Erreur");else void charger()}
 return <><AdminPageHeader title="Utilisateurs" description="Comptes DockFlow gérés par Supabase Auth." action={<button onClick={()=>setOpen(!open)} className="rounded-xl bg-[#78BE20] px-5 py-3 font-bold text-white">+ Nouvel utilisateur</button>}/>{message&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{message}</p>}{open&&<form onSubmit={submit} className="mb-6 grid gap-3 rounded-3xl border border-[#E3E8EC] bg-white p-5 md:grid-cols-2"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" className="min-h-12 rounded-xl border px-4"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mot de passe temporaire" className="min-h-12 rounded-xl border px-4"/><select value={role} onChange={e=>setRole(e.target.value)} className="min-h-12 rounded-xl border px-4"><option>RR</option><option>CARISTE</option><option>ADMIN</option></select><input value={magasinId} onChange={e=>setMagasinId(e.target.value)} placeholder="Identifiant magasin" className="min-h-12 rounded-xl border px-4"/><button disabled={loading} className="rounded-xl bg-[#78BE20] px-5 py-3 font-bold text-white">{loading?"Création...":"Créer"}</button></form>}<section className="overflow-x-auto rounded-3xl border border-[#E3E8EC] bg-white"><table className="min-w-full text-left"><thead className="bg-[#F6F8FA]"><tr><th className="p-4">E-mail</th><th className="p-4">Rôle</th><th className="p-4">Magasin</th><th className="p-4">Scope</th><th className="p-4">Statut</th><th className="p-4">Action</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id} className="border-t"><td className="p-4">{p.email}</td><td className="p-4">{p.role}</td><td className="p-4">{p.magasin_id??"—"}</td><td className="p-4">{p.admin_scope??"—"}</td><td className="p-4">{p.actif?"Actif":"Désactivé"}</td><td className="p-4"><button onClick={()=>toggle(p)} className="rounded-lg border px-3 py-2">{p.actif?"Désactiver":"Réactiver"}</button></td></tr>)}</tbody></table></section></>; }
